Updated Docker 4 Drupal to 5.3.3
ramsalt/drupal-project pull request #10
Opened 2018-11-16 12:20 UTC by kolibrid

2018-11-16 13:26 UTC, esolitos commented
The `.travis.yml` file should not be updated, it's now running the wrong tests. :)

2018-11-19 07:17 UTC, esolitos requested changes
Good work, but some small changes required before the merge. :)

2018-11-19 07:17 UTC, esolitos commented on docker-compose.yml
> -      - ./:/var/www/html:cached
@kolibrid As we all use MacOS the default options should use the `:cached` option, which greatly improves performances.

2018-11-19 07:17 UTC, esolitos commented on docker-compose.yml
> +      - ./:/var/www/html
Same as above, `:cached` option should be set,

2018-11-19 07:17 UTC, esolitos commented on docker-sync.yml
> +version: "2"
Docker-sync is not required anymore as Docker on MacOS has improved performances just by using the `:cached` option on mounted volumes.
Meaning: this file is not needed.

2018-11-19 07:36 UTC, kolibrid commented
Good that you remembered! I will fix it now.

2018-11-19 07:52 UTC, esolitos approved these changes

2018-11-19 07:54 UTC, merged